### ISSUE TITLE
Differentiate enemy kill sounds

### ISSUE THREAD

**Issue by vincetiu8** [Invincibot/covid-tower-defense#154]
Should we do this?

Currently, we have the ability to, I just put all the enemy sound files as the same sound. Maybe it would sound more interesting if we had different death sounds for each enemy. All we have to do is replace the enemy sound file. No coding required.

**Comment by Graphcalibur** [comment]
I don't think it's that necessary since a lot of enemies are basically cannon fodder. Maybe each "group" of enemies (e.g. flying enemies, explode-on-death enemies) have their own unique death sound but the enemies in the group have the same death sound. If we ever make any boss enemies, they can have their own special death sound.

**Comment by vincetiu8** [comment]
Ok cool.
