### ISSUE TITLE
Change coronavirus to another enemy

### ISSUE THREAD

**Issue by vincetiu8** [Invincibot/covid-tower-defense#276]
Some levels may now be extremely hard due to the recent buff to the coronavirus.

**Comment by Graphcalibur** [comment]
Actually I was planning to just reduce the amount of coronaviruses in the levels since there aren't any alternatives for shieldless/non-flying/non-exploding high HP enemies besides the even bulkier MRSA.

I was also thinking the coronavirus HP could be lowered a bit to 750 or something. This would make it easier to introduce in early levels and also differentiate it more from the MRSA.

**Comment by vincetiu8** [comment]
Perhaps sure! Go for it!

I'll work on adding another intermediary enemy. I think we need a few.
